import Vue from 'vue'
import {vuexfireMutations, firestoreAction} from 'vuexfire'
import Vuex from 'vuex'
import {db} from '../firebase/db'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    beleuchtung: [
    ],
    mikrofone: [
      "Shure Beta 52",
      "Shure Beta 57",
      "Shure Beta 98 H Clip",
      "Shure SM 57",
      "Shure SM 58",
      "Shure Beta 57",
      "Shure Beta 58",
      "Shure KSM 9",
      "Shure Beta 91",
      "Sennheiser e902",
      "Sennheiser e904",
      "Sennheiser e906",
      "Sennheiser e912",
      "Sennheiser MKH 50",
      "Sennheiser MKH 416",
      "Sennheiser MKH 815",
      "Sennheiser MD 421",
      "Sennheiser MD 431",
      "Sennheiser MD 441",
      "EV RE 20",
      "AKG C414",
      "AKG C1000",
      "Schoeps MK4",
      "Schoeps 03 CG",
      "Schoeps 3",
      "Neumann KM 84",
      "Neumann KMS 105",
      "Taschensender",
      "Handsender",
      "Mono DI Box",
      "Stereo DI Box",
    ],
    boxen: [
      "Nexo PS10",
      "Nexo PS10 Sub",
      "Nexo PS15",
      "Nexo PS10 Amp",
      "Nexo PS15 Amp",
      "Meyer Sound HP 500",
      "Meyer Sound HP 700",
      "Meyer Sound UPA",
      "Meyer Sound UP Junior",
      "Meyer Sound UPQ",
    ],
    tonpulte: [
      "Yamaha CL5",
      "Yamaha QL1",
      "Yamaha LS9",
      "Soundcraft VI 1",
      "Soundcraft VI 3000",
      "Behringer X32",
      "RBW",
    ],
    buehnentechnik: [
      "Bühnenpodest 2x1 m",
      "FD 33 Traverse",
      "FD 34 Traverse",
      "Tisch",
      "Trapetstisch",
      "Stuhl",
      "Rosconi Stellwand",
      "PLS",
      "Rednerpult",
      "Gaderobenständer",
      "Operafolie",
      "Scherenpdest 2x1 m",
      "Yamaha Klavier",
      "Tanzteppich",
      "Bistrotische",
      "Stehtische",
      "Tischverkleidung",
      "Ausstellungswand blau",
      "Multifunktionsstehpult",
      "Flipchart",
      "Barhocker",
      "Chorpodest",
      "Lederschwinger",
      "Beistelltisch",
      "Leinwand",
      "Sitzgruppe blau",
      "Außenbühne",
      "Roell Ausstellugnssystem",
      "Banner",
    ],
    scheinwerfer: [
      "JB Lighting P18",
      "JB Lighting A12",
      "JB Lighting A7",
      "Clay Paky Alpha Spot 800",
      "Clay Paky Alpha Profile 800",
      "Martin MAC TW1",
      "Astera AX5",
      "Astera AX10",
      "Showtec Sunstripe",
      "SGM P5",
      "Pixeltracks",
      "ETC Paletta",
      "ETC Source 4 LED",
      "Litecraft OutPAR AT10",
      "PAR 64",
      "PAR Stangen",
      "ETC Source 4",
      "Robert Juliat Profiler 1KW",
      "Robert Juliat Profiler 2KW",
      "Robert Juliat PC 1 KW",
      "Robert Juliat PC 2,5 KW",
      "Robert Juliat ALEX Halogen",
      "Robert Juliat ALEX HMI",
      "Selecon Pacific",
      "Stufenlinse 650W",
      "Stufenlinse 1KW",
      "Stufenlinse 2KW",
      "Stufenlinse 5KW",
      "Altmann Profiler 2KW",
      "Fluter 2KW Symmetrisch",
      "Fluter 2KW Asymmetrisch",
    ],
    kabel: [
      "DMX",
      "XLR",
      "Speakon",
      "Powercon",
      "Powercon True 1",
      "Schuko",
      "CEE 16A",
      "CEE 32A",
      "CEE 63A",
      "CEE 125A",
      "Kaltgeräte",
      "Cat 5",
      "HDMI",
      "DVI",
      "Glasfaser",
      "SDI",
    ]
  },
  mutations: vuexfireMutations,
  actions: {
  },
  modules: {
  }
})
